dbt_project:
  outputs:
    dev:

      type: snowflake
      account: "{{ env_var('NVJRCSG.LQ57629', '') }}"

      # User/password auth
      user: VARUN
      password: "{{ env_var('Bangam@12345', '') }}"

      role:   ACCOUNTADMIN
      database: AIRBYTE
      warehouse: COMPUTE_WH
      schema: VARUN_AIRBYTE
      threads: 1
      client_session_keep_alive: False
      query_tag: anything

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)

  target: dev
